#企业微信配置
server:
  port: 96
wechat:
  agentID: 1000039
  secretID: E4OTJRQlRbDf0KM6C_81f7ajPwdznE3e0q2m_4WqbcQ
  corpID: ww3b6376e85fb19ee9
  tokenUrl: http://10.185.15.24:56780/cgi-bin/gettoken?corpid=
  userInfoUrl: http://10.185.15.24:56780/cgi-bin/user/getuserinfo?access_token=
  userDetailUrl: http://10.185.15.24:56780/cgi-bin/user/get?access_token=
  departmentListUrl: http://10.185.15.24:56780/cgi-bin/department/list?access_token=
  ticket: http://10.185.15.24:56780/cgi-bin/ticket/get?access_token=
  jsapiTicket: http://10.185.15.24:56780/cgi-bin/get_jsapi_ticket?access_token=
  redirectUrl: http://222.178.134.41:56782/unnetdisk-server/mobile/?access_token=
  uploadUrl: http://10.185.15.24:56780/cgi-bin/media/upload?access_token=
  sendUrl: http://10.185.15.24:56780/cgi-bin/message/send?access_token=


spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://172.18.1.126:4306/netdisk?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: mysql4unnet2docker
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 6
      minIdle: 6
      maxActive: 20

minio:
  endpoint: http://develop.cq.un-net.com:9000/
  access-key: 0ZN2SLW1WFGXWXZ6KPJ6
  secret-key: 8NzkXK3CUfKQ+Q3hpDDqnU+z8UIADrRmM5Silcgs

mybatis-plus:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:/mapper/*.xml
  # 注意：对应实体类的路径//entity扫描的包名
  type-aliases-package: unnet.weixin.netdisk.entity
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    banner: false
swagger:
  enable: false